/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RyanGUIProject2;

import my.zhugui2.ZhuGUI2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ZhuGUI2.main(args);
    }
}
